package com.tradingbot.backend.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

/**
 * Represents a trading signal generated by a strategy
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TradeSignal {
    // Trading pair symbol (e.g., BTCUSDT)
    private String symbol;
    
    // Current price when signal was generated
    private double price;
    
    // Timestamp of when the signal was generated
    private long timestamp;
    
    // Name of the strategy that generated this signal
    private String strategyName;
    
    // Trade decision (BUY, SELL, HOLD)
    private TradeDecision decision;
    
    // Explanation of why this signal was generated
    private String rationale;
    
    // Confidence score (0.0-1.0) indicating signal strength
    private double confidence;
    
    // Optional additional data specific to the strategy
    private Object additionalData;
} 